# List of groups to create via the API
groups:

# Standard waste containers, 1.5m deep
- entity_type: wasteContainer
  apikey: wc_molukas_containers_1.5m
  protocol:
  - IoTA-JSON
  attributes:
  - name: areaServed
    type: string
  - name: category
    type: array
    # Possible values:
    #- fixed
    #- underground
    #- ground
    #- portable
    #- other
  - name: containerIsle
    type: string
  - name: description
    type: string
  - name: isleId
    type: string
  - name: location
    type: "geo:point"
  - name: refWasteContainerModel
    type: string
  - name: serialNumber
    type: string
  - name: status
    type: string
    # Possible values:
    #- ok
    #- lidOpen
    #- dropped
    #- moved
    #- vandalized
    #- burning
    #- unknown
  - name: storedWasteKind
    type: string
    # Possible values:
    #- organic
    #- inorganic
    #- glass
    #- oil
    #- plastic
    #- metal
    #- paper
    #- batteries
    #- electronics
    #- hazardous
    #- other
  - name: storedWasteOrigin
    type: string
    # Possible values:
    #- household
    #- municipal
    #- industrial
    #- construction
    #- hostelry
    #- agriculture
    #- other
  - name: dateLastEmptying
    type: "date"
  - name: dateUpdated
    type: "date"
  - name: dateNextActuation
    type: "date"
  - name: weight
    type: float
  - name: methaneConcentration
    type: float
  - name: fillingLevel
    type: float
    expression: "${(150 - @fillingLevel) / 150}"
    object_id: h
  - name: temperature
    type: float
    object_id: t

# List of entities to create via the API
entities:

# First test container
- device_id: wc_molukas_container_1
  entity_name: wc_molukas_container_1
  protocol: IoTA-JSON
  _inherit:
  - apikey: wc_molukas_containers_1.5m
    values:
      areaServed: "Calle test 1"
      category: ['ground']
      containerIsle: isla1
      description: Contenedor superficie de 1.5 metros
      isleId: isla1
      location: 28.999880, -13.611424
      refWasteContainerModel: wcm_molukas_model_1
      serialNumber: 123456
      status: unknown
      storedWasteKind: organic
      storedWasteOrigin: household
      dateLastEmptying: "1900-01-01"
      dateUpdated: "1900-01-01"
      dateNextActuation: "1900-01-01"
      weight: 0
      methaneConcentration: 0

# Second test container
- device_id: wc_molukas_container_2
  entity_name: wc_molukas_container_2
  protocol: IoTA-JSON
  _inherit:
  - device_id: wc_molukas_container_1
    values:
      areaServed: "Calle test 2"
      containerIsle: isla2
      isleId: isla2
      location: 28.996589, -13.612841
      serialNumber: 654321
