# List of entities to create via the API
entities:

# Modelo de contenedores marca Molukas modelo test
- device_id: wcm_molukas_model_1
  entity_type: wasteContainerModel
  entity_name: wcm_molukas_model_1
  protocol: IoTA-JSON
  attributes:
  - name: brandName
    type: string
    value: molukas
  - name: modelName
    type: string
    value: test
  - name: madeOf
    type: string
    value: plastic
    # Possible values:
    #- plastic
    #- wood
    #- metal
    #- other
  - name: width
    type: float
    value: 2
  - name: height
    type: float
    value: 1.5
  - name: depth
    type: float
    value: 1
  - name: maximumLoad
    type: float
    value: 0.95
  - name: volumeStored
    type: float
    #expression: "${@width*@height*@depth*@maximumLoad}"
    value: 2.85
  